import "bootstrap/dist/css/bootstrap.min.css"; 
import "aos/dist/aos.css"; 
import "@/app/style/AppBar.css"; 
import ClientComponent from "./(pages)/ClientComponent";



// Define metadata for the layout
export const metadata = {
  title: "Tyent India",
  description: "Generated by create next app",
};

export default function RootLayout({ children, session }) {

  return (
    <html lang="en">
      <body style={{ fontFamily: "Poppins, sans-serif" }}>
        <ClientComponent session={session}>
          {children}
        </ClientComponent>
      </body>
    </html>
  );
}