import "bootstrap/dist/css/bootstrap.min.css"; 
import "aos/dist/aos.css"; 
import "@/app/style/AppBar.css"; 
import dynamic from "next/dynamic";
import { Poppins} from 'next/font/google'
import Head from "next/head";
 
const poppins = Poppins({
  weight: '400',
  subsets: ['latin'],
})
 
const ClientComponent = dynamic(() => import("./(pages)/ClientComponent"),{ssr:false})




// Define metadata for the layout
export const metadata = {
  title: "Tyent India",
  description: "Generated by create next app",
};

export default function RootLayout({ children, session }) {

  return (
    <html lang="en">
     
      <body  className={poppins.className} style={{backgroundColor:'#f8fbfe', overflowX:'hidden', width:'100%'}}>
        <ClientComponent session={session}>
          {children}
        </ClientComponent>
      </body>
    </html>
  );
}