import React from "react";
import { Container, Row, Col } from "react-bootstrap";
import { CiLocationOn } from "react-icons/ci";
import dynamic from "next/dynamic";
import AskyourQuery from "@/asserts/contact/AskyourQuery.webp";
import DealerEnquiry from "@/asserts/contact/DealerEnquiry.webp";
import productDemo from "@/asserts/contact/productDemo.webp";
import ServiceRequest from "@/asserts/contact/ServiceRequest.webp";
import Image from "next/image";
import contactUsBanner from "@/asserts/contactUsBanner.png";

const Header = dynamic(() => import("../compoents/Header"), {
  ssr: false,
});

export const metadata = {
  title: "Contact page",
  description: "Generated by create next app",
};

const headerData = {
  preheading:'Trust, Care & Commitment',
  afterheading: "We're happy to help!",
  img: contactUsBanner,
  animatedText: "Have Questions ?, Need Assistance ? ",
};



const InfoCard = ({ icon: Icon, title, text }) => (
  <Col xs={12} md={4} style={{ padding: "20px" }}>
    <div className="custom-card">
      <p
        className="m-0"
        style={{ fontSize: "20px", fontWeight: 600, padding: "10px" }}
      >
        {title}
      </p>
      <div className="d-flex align-items-top">
        <div className="contennticon p-1">
          <Icon
            size={20}
            style={{
              backgroundColor: "#008ac7",
              color: "#FFF",
              width: "50px",
              height: "50px",
              borderRadius: "50%",
              padding: "10px",
            }}
          />
        </div>
        <div className="content align-items-top">
          <div
            className="text p-1"
            dangerouslySetInnerHTML={{ __html: text }}
          />
        </div>
      </div>
    </div>
  </Col>
);

const Page = () => {

  const items = [
    { src: productDemo, alt: "Product Demo", title: "Product Demo" },
    { src: DealerEnquiry, alt: "Dealer Enquiry", title: "Dealer Enquiry" },
    { src: ServiceRequest, alt: "Service Request", title: "Service Request" },
    { src: AskyourQuery, alt: "Ask your Query", title: "Ask your Query" },
  ];


  return (
    <div>
      <Header
        basic={headerData.basic}
        preheading={headerData.preheading}
        afterheading={headerData.afterheading}
        content={headerData.content}
        img={headerData.img}
        animatedText={headerData.animatedText} // Passing dynamic animated text
      />
      <Container>
        <div className="section-spacing">
          <h3
            className="m-0 text-center"
            style={{ color: "#008AC7", fontWeight: "600" }}
            data-aos="fade-down"
          >
            You can find us here!{" "}
          </h3>
          <p className="text-center" style={{ fontSize: "20px" }}>
            We would love to connect with you
          </p>
          <br />
          <Row className="g-4">
            {items.map((item, index) => (
              <Col
                key={index}
                md={3}
                sm={6}
                xs={6}
                className="text-center"
                data-aos="zoom-in"
              >
                <div>
                  <Image
                    src={item.src}
                    alt={item.alt}
                    layout="responsive"
                    priority
                    style={{ borderRadius: "20px" }}
                  />
                  <h5 className="mt-3">
                    <b>{item.title}</b>
                  </h5>
                </div>
              </Col>
            ))}
          </Row>
        </div>

        <div className="section-spacing" data-aos="fade-up">
          {/* First Row */}
          <Row>
            {" "}
            {/* Added grid gap and bottom margin for row */}
            <InfoCard
              icon={CiLocationOn}
              title="Corporate Head office:"
              text="8-277/45, UBI Colony,
           Banjara Hills Rd Number 3, Hyderabad, Telangana - 500034.
           Landmark:  Near TV9 news office"
            />
            <InfoCard
              icon={CiLocationOn}
              title="Tyent Delhi"
              text=" Mahadev Enterprises, 
              Room no 2 , Merry building, 
            Liberty garden no 3, 
              Near moreshwar dham Building,
            Malad west Mumbai - 400064."
            />
            <InfoCard
              icon={CiLocationOn}
              title="Tyent Mumbai"
              text={`Mahadev Enterprises, 
Room no 2 , Merry building, 
Liberty garden no 3, 
Near moreshwar dham Building,
Malad west Mumbai - 400064.`}
            />
            <InfoCard
              icon={CiLocationOn}
              title="Tyent Ahmadabad"
              text="Mahadev Enterprises, 
Room no 2 , Merry building, 
Liberty garden no 3, 
Near moreshwar dham Building,
Malad west Mumbai - 400064."
            />
            <InfoCard
              icon={CiLocationOn}
              title="Tyent Sikhar"
              text={`Mahadev Enterprises, 
Room no 2 , Merry building, 
Liberty garden no 3, 
Near moreshwar dham Building,
Malad west Mumbai - 400064.`}
            />
            <InfoCard
              icon={CiLocationOn}
              title="Tyent UP"
              text="Mahadev Enterprises, 
Room no 2 , Merry building, 
Liberty garden no 3, 
Near moreshwar dham Building,
Malad west Mumbai - 400064."
            />
          </Row>
        </div>
      </Container>
    </div>
  );
};

export default Page;
