import React from 'react';
import { Container, Row, Col } from 'react-bootstrap';
import { CiLocationOn } from "react-icons/ci";
import dynamic from "next/dynamic";
import certification from "@/asserts/certifications/certification.png"
import AskyourQuery  from "@/asserts/contact/AskyourQuery.png"
import DealerEnquiry  from "@/asserts/contact/DealerEnquiry.png"
import productDemo   from "@/asserts/contact/productDemo.png"
import ServiceRequest from "@/asserts/contact/ServiceRequest.png"
import Image from 'next/image';


const Header = dynamic(() => import('../compoents/Header'), {
  ssr: false,
});


export const metadata = {
  title: "Contact page",
  description: "Generated by create next app",
};



const headerData = { 
  basic: "Trust, Satisfaction & Transformations",
  preheading:'Hear From Our Real',
  afterheading: "Satisfied Tyent India Customers",
  content: "At Tyent India, we take immense pride in the health transformations and positive lifestyle changes our customers experience through our hydrogen-rich alkaline water. Our cutting-edge water ionizers are designed to provide superior antioxidant support, better hydration, and long-term wellness. But don’t just take our word for it - hear it from those who matter most, our valued customers!",
  img: certification,
  animatedText: "Health, Wellness, Transformation" // Pass the animated text here
}


const InfoCard = ({ icon: Icon, title, text }) => (
  <Col xs={12} md={4} style={{padding:'20px'}}>
    <div className="custom-card">
    <p className='m-0' style={{fontSize:'20px', fontWeight:600, padding:'10px'}}>{title}</p>
    <div className='d-flex align-items-top p-1'>
      <div className="contennticon" ><Icon size={20} style={{backgroundColor:'#008ac7', color:'#FFF',width:'60px', height: '60px', borderRadius:'50%', padding:'10px' }} /></div>
      <div className="content p-2">
        <div className="text" dangerouslySetInnerHTML={{ __html: text }} />
      </div>
    </div>
    </div>
  </Col> 
);

const Page = () => {
  return (
    <div>
      <Header 
        basic={headerData.basic} 
        preheading={headerData.preheading} 
        afterheading={headerData.afterheading}
        content={headerData.content} 
        img={headerData.img}
        animatedText={headerData.animatedText} // Passing dynamic animated text
      />
      <Container>

         <Row>
          <Col md={3} xs={2} className='p-3'>
          <div>
          <Image src={productDemo} alt="AskyourQuery"  layout="responsive" priority  style={{borderRadius:'20px'}}/>
          <h5 className='text-center m-4'><b>Product Demo</b></h5>
          </div>
          </Col>
          <Col md={3} xs={2} className='p-3'>
          <div>
          <Image src={DealerEnquiry} alt="AskyourQuery"  layout="responsive" priority  style={{borderRadius:'20px'}}/>
          <h5 className='text-center m-4'><b>Dealer Enquiry</b></h5>
          </div>
          </Col>
          <Col md={3} xs={2} className='p-3'>
          <div>
          <Image src={ServiceRequest} alt="AskyourQuery"  layout="responsive" priority style={{borderRadius:'20px'}}/>
           <h5 className='text-center m-4'><b>Service Request</b></h5>
          </div>
          </Col>
          <Col md={3} xs={2} className='p-3'>
          <div>
          <Image src={AskyourQuery} alt="AskyourQuery"  layout="responsive" priority style={{borderRadius:'20px'}}/>
          <h5 className='text-center m-4'><b>Ask your Query</b></h5>
          </div>
          </Col>
         </Row>

        <br/>
        
        {/* First Row */}
        <Row> {/* Added grid gap and bottom margin for row */}
          <InfoCard
            icon={CiLocationOn}
            title="Corporate Head office:"
            text="8-277/45, UBI Colony,
           Banjara Hills Rd Number 3, Hyderabad, Telangana - 500034.
           Landmark:  Near TV9 news office"
          />
          <InfoCard
            icon={CiLocationOn}
            title="Tyent Delhi - Head office"
            text=" Mahadev Enterprises, 
              Room no 2 , Merry building, 
            Liberty garden no 3, 
              Near moreshwar dham Building,
            Malad west Mumbai - 400064."
          />
          <InfoCard
            icon={CiLocationOn}
            title="Tyent Mumbai - Head office"
            text={`Mahadev Enterprises, 
Room no 2 , Merry building, 
Liberty garden no 3, 
Near moreshwar dham Building,
Malad west Mumbai - 400064.`}
          />
          <InfoCard
            icon={CiLocationOn}
            title="Tyent Ahmadabad - Head office"
            text="Mahadev Enterprises, 
Room no 2 , Merry building, 
Liberty garden no 3, 
Near moreshwar dham Building,
Malad west Mumbai - 400064."
          />
          <InfoCard
            icon={CiLocationOn}
            title="Tyent Sikhar - Head office"
            text={`Mahadev Enterprises, 
Room no 2 , Merry building, 
Liberty garden no 3, 
Near moreshwar dham Building,
Malad west Mumbai - 400064.`}
          />
          <InfoCard
            icon={CiLocationOn}
            title="Tyent UP - Head office"
            text="Mahadev Enterprises, 
Room no 2 , Merry building, 
Liberty garden no 3, 
Near moreshwar dham Building,
Malad west Mumbai - 400064."
          />
        </Row>


      </Container>

    </div>
  );
};

export default Page;
