import React from "react";
import dynamic from "next/dynamic";
import { Col, Row } from "react-bootstrap";
import icon from "@/asserts/Testmonials/icon1.png";
import Image from "next/image";
import certification from "@/asserts/certifications/certification.png"
const RWebShareComp = dynamic(() => import("../compoents/RWebShare"), {ssr: false});
const Header = dynamic(() => import("../compoents/Header"), {ssr: false});


export const metadata = {
  title: "Testimonial page",
  description: "Generated by create next app",
}; 



const videos = [
  {
    id: 1,
    src: "https://www.youtube.com/embed/-xXUDPQVQfY?rel=0&modestbranding=1",
    description:
      "Akhil Bansal's Honest Comparison: Enagic Kangen vs. Tyent Ionizers",
  },
  {
    id: 2,
    src: "https://www.youtube.com/embed/EHOzAr4H3nU?rel=0",
    description:
      "Unlocking Wellness: Tyent Water Ionizer Testimony from Pune",
  },
  {
    id: 3,
    src: "https://www.youtube.com/embed/o9N4evESgPU?rel=0",
    description:
      "Colonel Vishnu Singh Rawal Sir Reviews Tyent Ionizer: The Ultimate Health Solution",
  },
  {
    id: 4,
    src: "https://www.youtube.com/embed/hcSywpiWZy0?rel=0",
    description:
      "𝐀𝐧𝐯𝐞𝐬𝐡 𝐏𝐚𝐭𝐞𝐥's Personal Experience: 𝐓𝐲𝐞𝐧𝐭 Water Ionizer - The Perfect Solution",
  },
  {
    id: 5,
    src: "https://www.youtube.com/embed/4gVHb-XcjTA?rel=0",
    description:
      "𝐒𝐮𝐝𝐡𝐚𝐤𝐚𝐫𝐚 𝐍𝐞𝐞𝐥𝐚𝐦's honest Testimony after using 𝐓𝐲𝐞𝐧𝐭 Water Ionizer for 4 Years",
  },
  {
    id: 6,
    src: "https://www.youtube.com/embed/Jcwaqs2K1sk?rel=0",
    description:
      "𝐓𝐲𝐞𝐧𝐭 - 𝐌𝐲 𝐒𝐞𝐜𝐫𝐞𝐭 𝐭𝐨 𝐇𝐞𝐚𝐥𝐭𝐡 𝐚𝐧𝐝 𝐑𝐚𝐝𝐢𝐚𝐧𝐭 𝐒𝐤𝐢𝐧 - 𝐒𝐞𝐧𝐢𝐨𝐫 𝐀𝐜𝐭𝐫𝐞𝐬𝐬 𝐒𝐡𝐚𝐧𝐨𝐨𝐫 𝐒𝐚𝐧𝐚 𝐆𝐚𝐫u",
  },
  {
    id: 7,
    src: "https://www.youtube.com/embed/4bSRX0eA8kE?rel=0",
    description:
      "𝐒𝐮𝐛𝐡𝐚's Journey of Weight Loss & Reversing Diabetes with 𝐓𝐲𝐞𝐧𝐭",
  },
  {
    id: 8,
    src: "https://www.youtube.com/embed/3Qi2Bp8gB6M?rel=0",
    description:
      "𝐒𝐮𝐝𝐡𝐚 𝐒𝐫𝐢𝐧𝐢𝐯𝐚𝐬 𝐆𝐚𝐫𝐮 (CFO at NMDC) Shares Health Benefits and Service Experience with 𝐓𝐲𝐞𝐧𝐭 ",
  },
  {
    id: 9,
    src: "https://www.youtube.com/@TyentIndia3170",
    description:
      "Visit our YouTube channel for more video testimonials",
  },
  
];

const icons = [
  {
    id: 1,
    icon: icon,
    name: "Sai korrapati",
    designation: "Actor",
  },
  {
    id: 2,
    icon: icon,
    name: "Venu thottempudi",
    designation: "Actor",
  },
  {
    id: 3,
    icon: icon,
    name: "VV Vinayak",
    designation: "Film Director",
  },
  {
    id: 4,
    icon: icon,
    name: "Sana Shanoor",
    designation: "Film Actress",
  },
  {
    id: 5,
    icon: icon,
    name: "Jagdeep Dhankar",
    designation: "VP",
  },
  {
    id: 6,
    icon: icon,
    name: "Ramalinga Reddy",
    designation: "Transport Minister of Karnataka.",
  },
  {
    id: 7,
    icon: icon,
    name: "Vasupalli Ganesh Kumar",
    designation: "EX- MLA",
  },
  {
    id: 8,
    icon: icon,
    name: "Robin Uttapa",
    designation: "Canadian Film Actor",
  },
  {
    id: 9,
    icon: icon,
    name: " Mr. M. Madan Mohan Reddy",
    designation: "Whole Time Director, Aurobindo",
  },
  {
    id: 10,
    icon: icon,
    name: "V. Saveen",
    designation: "Awarded Natural Bodybuilder, FITT Studio",
  },
  {
    id: 11,
    icon: icon,
    name: "DV Rao",
    designation: "MD, VSP Industries",
  },
  {
    id: 12,
    icon: icon,
    name: "Addanki Dayakar",
    designation: "Ex-MLA",
  },
  {
    id: 13,
    icon: icon,
    name: "Padmaja Lanka",
    designation: "Film Actress",
  },
  {
    id: 14,
    icon: icon,
    name: "Dr. Pradeep Kumar",
    designation: "Commissioner Customs & GST",
  },
  {
    id: 15,
    icon: icon,
    name: "N C Naga raj ",
    designation: "EX-DSP Thumkur - KA",
  },
  {
    id: 16,
    icon: icon,
    name: "muzeef",
    designation: "Canadian Film Actor",
  },
  {
    id: 17,
    icon: icon,
    name: "muzeef",
    designation: "Canadian Film Actor",
  },
  {
    id: 18,
    icon: icon,
    name: "muzeef",
    designation: "Canadian Film Actor",
  },
  {
    id: 19,
    icon: icon,
    name: "muzeef",
    designation: "Canadian Film Actor",
  },
];


const VideoCard = ({ src, description }) => {
  return (
    <div
      className="custom-card text-center"
      style={{ padding: "10px" }}
      data-aos="fade-up"
    >
      <div className="embed-responsive embed-responsive-16by9 mb-3">
        <iframe
          className="embed-responsive-item"
          src={src}
          style={{ borderRadius: "8px", width: "100%", height: "210px" }}
          allowFullScreen
          title="Video"
        />
      </div>
      <div
        style={{
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
        }}
      >
        <h6 className="text-start" style={{ flexGrow: 1 }}>
          {description}
        </h6>
        <RWebShareComp text={description} link={src} />
      </div>
    </div>
  );
};

const IconTest = ({ name, icon, designation }) => {
  return (
    <div data-aos="zoom-in">
      <div>
        <center>
          <Image
            src={icon}
            priority
            style={{ width: "120px", height: "120px" }}
            alt={designation}
          />
        </center>
      </div>

      <h5 className="text-center mt-2" style={{ flexGrow: 1 }}>
        {name}
      </h5>
      <p className="text-center mt-2" style={{ flexGrow: 1, color:'#008AC7' }}>
        {designation}
      </p>
    </div>
  );
};

const Page = () => {
  const headerData = {
    basic: "Trust, Satisfaction & Transformations",
    preheading: "Hear From Our Real",
    afterheading: "Satisfied Tyent India Customers",
    content:
      "At Tyent India, we take immense pride in the health transformations and positive lifestyle changes our customers experience through our hydrogen-rich alkaline water. Our cutting-edge water ionizers are designed to provide superior antioxidant support, better hydration, and long-term wellness. But don’t just take our word for it - hear it from those who matter most, our valued customers!",
    img: "path/to/image.jpg", // Add image URL if needed
    animatedText: "Health, Wellness, Transformation", // Pass the animated text here
  };

  return (
    <div>
      <Header
        basic={headerData.basic}
        preheading={headerData.preheading}
        afterheading={headerData.afterheading}
        content={headerData.content}
        img={certification}
        animatedText={headerData.animatedText}
      />
      <div className="container">
        <Row className="gy-3">
          {videos.map((video) => (
            <Col md={4} sm={6} key={video.id}>
              <VideoCard src={video.src} description={video.description} />
            </Col>
          ))}
        </Row>
        <br />
        <h2 className="text-center">
          "
          <span style={{ fontWeight: 600, color: "#008AC7" }}>
            Trusted by Icons:
          </span>{" "}
          Influential Voices on Tyent Water"
        </h2>
        <Row className="gy-3">
          {icons.map((iconItem) => (
            <Col md={2} key={iconItem.id}>
              <IconTest
                icon={iconItem.icon}
                name={iconItem.name}
                designation={iconItem.designation}
              />
            </Col>
          ))}
        </Row>
      </div>
    </div>
  );
};

export default Page;
